version: '3'
services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9100:9100"
    command: tail -f /dev/null
    volumes:
      - .:/root/project
    deploy:
      resources:
        limits:
          memory: 2G

  elasticsearch:
    container_name: elastic
    image: elasticsearch:7.17.20
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  esdata: