version: '3'
services:
  sqlite:
    container_name: sqlLite
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9100:9100"
    command: tail -f /dev/null
    volumes:
      - .:/root/project

  elasticsearch:
    container_name: elastic
    image: elasticsearch:7.17.20
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: